### ISSUE TITLE
[Question/Maybe Bug] namespacing

### ISSUE THREAD

**Issue by blipson89** [kamsar/Leprechaun#3]
I'm in a situation right now where an item is located at `/sitecore/templates/Feature/Navigation/Menu Item`. In the roslyn code gen file, `{template.CodeName}` is returning `Menu Item` rather than `MenuItem`. I was able to determine that if I put a folder inbetween `Navigation` and `Menu Item` (i.e. `/sitecore/templates/Feature/Navigation/Metadata/Menu Item`, `{template.CodeName}` appropriately becomes `MenuItem`

I tracked it down to this if statement:
https://github.com/kamsar/Leprechaun/blob/e0a23cb499d11656d2ef1729ed0e8c6da4a31da4/src/Leprechaun/MetadataGeneration/StandardTypeNameGenerator.cs#L48

`name` = `Menu Item`. Since there's no `.`, it doesn't go through `ConvertToIdentifier()`, which would remove the spaces. 

Is there a reason it's like this, or should I open a PR in which this situation is handled?

**Comment by kamsar** [comment]
1) bug
2) yes, please fix it

**Comment by kamsar** [comment]
Closing in favor of PR
